import { Activity, ArrowRight, Check, CheckCircle2, MessageCircle, Package, RefreshCw, Sparkles, Target, TrendingUp, Users, X } from "lucide-react";
import { Link, useLocation } from "wouter";
import { Badge, Button, Card, PageHeader, SectionTitle, Avatar } from "@/components/product-ui";
import { useBusiness } from "@/business-context";
import { useWorkspaceData } from "@/hooks/use-workspace-data";
import { money } from "@/lib/product-utils";

function Metric({ title, value, foot, icon, tone }: { title: string; value: string; foot: string; icon: React.ReactNode; tone: string }) {
  return <Card className="kpi"><div className="kpi-top"><span>{title}</span><div className={`kpi-icon ${tone}`}>{icon}</div></div><div className="kpi-value">{value}</div><div className="kpi-foot"><span className="trend-up">{foot.split(" ")[0]}</span><span>{foot}</span></div></Card>;
}

export function BusinessDashboardPage() {
  const { activeBusiness } = useBusiness();
  const { data, update, recordAudit, industry } = useWorkspaceData();
  const [, setLocation] = useLocation();
  const isRealEstate = industry === "Real Estate";
  const pending = data.approvals.filter((item) => item.status === "Pending");
  const unread = data.conversations.filter((item) => item.unread).length;
  const updateApproval = (id: number, status: "Approved" | "Rejected") => {
    const item = data.approvals.find((approval) => approval.id === id);
    update((current) => ({ ...current, approvals: current.approvals.map((approval) => approval.id === id ? { ...approval, status } : approval) }));
    if (item) recordAudit({ actor: "Alexandra Andria", actorType: "Human user", action: `${status} AI action`, entity: item.title, before: "Pending", after: status, status: "Completed", approval: `Approval #${id}`, source: "Dashboard" });
  };
  const recommendation = data.opportunities[0];
  return <>
    <PageHeader eyebrow="Today · AI team online" title={`Good morning, ${activeBusiness?.name}`} subtitle={`Here is what your AI Business Team found for ${activeBusiness?.name}.`} action={<div className="toolbar"><Link href="/reports/daily" className="btn btn-secondary">Daily report <ArrowRight /></Link><Button variant="soft" onClick={() => setLocation("/command")}><Sparkles /> Ask your manager</Button></div>} />
    <div className="grid kpi-grid"><Metric title={isRealEstate ? "Pipeline value" : "Today's revenue"} value={isRealEstate ? money(data.analytics.revenue, true) : "$4,820"} foot="+18% from last period" icon={<TrendingUp />} tone="green" /><Metric title={isRealEstate ? "Active listings" : "Pending orders"} value={isRealEstate ? String(activeBusiness?.products.length ?? 0) : String(data.orders.filter((item) => !["Delivered", "Cancelled"].includes(item.status)).length)} foot={isRealEstate ? "4 need attention" : "3 need attention"} icon={<Package />} tone="orange" /><Metric title="Unread messages" value={String(unread)} foot="Across connected channels" icon={<MessageCircle />} tone="brown" /><Metric title="New leads" value={String(data.analytics.leads)} foot={`${data.leads.filter((item) => item.score >= 85).length} high intent`} icon={<Target />} tone="rose" /></div>
    <div className="grid split-grid dashboard-primary"><Card className="health-card"><SectionTitle title="Business health" action={<Badge tone="success">Healthy</Badge>} /><div className="health-layout"><div><div className="score-ring"><div className="score-inner"><strong>{isRealEstate ? 84 : 87}</strong><span>out of 100</span></div></div><p className="health-caption">Stable momentum this week</p></div><div className="health-bars">{[["Sales", isRealEstate ? 88 : 92], ["Marketing", 81], ["Customers", 88], ["Support", 95], ["Operations", 84]].map(([label, value]) => <div className="health-row" key={String(label)}><span>{label}</span><div className="bar"><i style={{ width: `${value}%` }} /></div><strong>{value}</strong></div>)}</div></div></Card><Card className="recommendation"><SectionTitle title="AI recommendations" action={<Link href="/opportunities" className="btn btn-sm btn-soft">Review all <ArrowRight /></Link>} /><div className="recommendation-item"><div className="rec-icon"><RefreshCw /></div><div className="rec-title">{recommendation?.title}</div><div className="rec-copy">{recommendation?.copy}</div><div className="rec-value">Potential impact · {recommendation?.impact}</div></div><div className="recommendation-item"><div className="rec-icon"><TrendingUp /></div><div className="rec-title">{isRealEstate ? "Buyer education is outperforming listing-only content." : "Harvest engagement increased 32%."}</div><div className="rec-copy">{isRealEstate ? "Create a practical guide for the strongest current property signal." : "Create another field-to-table story while interest is warm."}</div><Button variant="green" className="btn-sm" onClick={() => setLocation("/cmo?tab=Content")}>Create content</Button></div></Card></div>
    <div className="grid three-grid dashboard-activity-grid"><Card><SectionTitle title="Approval tasks" action={<Link href="/approvals" className="subtle">View all</Link>} /><div className="list">{pending.slice(0, 3).map((item) => <div className="list-row" key={item.id}><div className="row-main"><div className="row-title">{item.title}</div><div className="row-copy">{item.agent} · {item.impact}</div></div><div className="toolbar"><Button variant="green" className="btn-sm" onClick={() => updateApproval(item.id, "Approved")}><Check /></Button><Button variant="danger" className="btn-sm" onClick={() => updateApproval(item.id, "Rejected")}><X /></Button></div></div>)}{!pending.length && <div className="empty compact-empty"><CheckCircle2 /><h3>All clear</h3><p>No actions are waiting for approval.</p></div>}</div></Card><Card><SectionTitle title="Recent conversations" action={<Link href="/conversations" className="subtle">View inbox</Link>} /><div className="list">{data.conversations.slice(0, 4).map((item) => <div className="list-row" key={item.id}><Avatar name={item.name} /><div className="row-main"><div className="row-title">{item.name} <span className="row-copy inline-copy">· {item.channel}</span></div><div className="row-copy">{item.message}</div></div><div className="time">{item.time}</div></div>)}</div></Card><Card><SectionTitle title="AI activity" action={<Link href="/agents/activity"><Activity /></Link>} />{data.agentActivity.slice(0, 4).map((item) => <div className="activity-line" key={item.id}><div className="activity-dot" /><div><div className="activity-time">{item.timestamp}</div><div className="activity-copy">{item.agent} · {item.action}</div></div></div>)}</Card></div>
    <SectionTitle title={isRealEstate ? "Recent opportunities & viewings" : "Recent orders"} action={<Link href="/orders" className="btn btn-sm btn-secondary">View all <ArrowRight /></Link>} /><Card className="table-card" pad={false}><div className="table-scroll"><table><thead><tr><th>Record</th><th>{isRealEstate ? "Contact" : "Customer"}</th><th>{isRealEstate ? "Property / activity" : "Items"}</th><th>Value</th><th>Status</th><th>Time</th></tr></thead><tbody>{data.orders.slice(0, 4).map((item) => <tr key={item.id}><td><strong>{item.id}</strong></td><td>{item.customer}</td><td>{item.items}</td><td><strong>{money(item.total)}</strong></td><td><Badge tone={item.status.includes("Delivered") || item.status.includes("Confirmed") ? "success" : "warning"}>{item.status}</Badge></td><td>{item.date}</td></tr>)}</tbody></table></div></Card>
  </>;
}

