import { useState } from "react";
import { BarChart3, MessageCircle, ShoppingBag, Sparkles, Target, TrendingUp, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useLocation } from "wouter";
import { Card, PageHeader, SectionTitle, Button } from "@/components/product-ui";
import { useWorkspaceData } from "@/hooks/use-workspace-data";
import { money } from "@/lib/product-utils";
import { demoWorkspaceDataEnabled } from "@/services/workspace-repository";

function Metric({ title, value, copy, icon, tone }: { title: string; value: string; copy: string; icon: React.ReactNode; tone: string }) {
  return <Card className="kpi"><div className="kpi-top"><span>{title}</span><div className={`kpi-icon ${tone}`}>{icon}</div></div><div className="kpi-value">{value}</div><div className="kpi-foot"><span className="trend-up">{copy.split(" ")[0]}</span><span>{copy}</span></div></Card>;
}

export function AnalyticsPage() {
  const { data, industry } = useWorkspaceData();
  const [, setLocation] = useLocation();
  const [range, setRange] = useState("Last 30 days");
  const analytics = data.analytics;
  const metricCopy = demoWorkspaceDataEnabled
    ? "+18% vs prior period"
    : "No live analytics API";
  const colors = ["#15803d", "#f97316", "#9bc9a6", "#d3a476", "#94a3b8"];
  return <>
    <PageHeader eyebrow="Intelligence" title="Business analytics" subtitle="See the signals beneath the day-to-day, then act on the clearest cause." action={<select className="business-select" value={range} onChange={(event) => setRange(event.target.value)}><option>Last 7 days</option><option>Last 30 days</option><option>Last 90 days</option></select>} />
    <div className="grid analytics-kpi-grid"><Metric title={industry === "Real Estate" ? "Pipeline value" : "Revenue"} value={money(analytics.revenue, true)} copy={metricCopy} icon={<TrendingUp />} tone="green" /><Metric title={industry === "Real Estate" ? "Active opportunities" : "Orders"} value={String(analytics.orders)} copy={metricCopy} icon={<ShoppingBag />} tone="orange" /><Metric title={industry === "Real Estate" ? "Contacts" : "Customers"} value={String(analytics.customers)} copy={metricCopy} icon={<Users />} tone="brown" /><Metric title="Leads" value={String(analytics.leads)} copy={metricCopy} icon={<Target />} tone="rose" /><Metric title="Conversion" value={`${analytics.conversion}%`} copy={metricCopy} icon={<BarChart3 />} tone="green" /><Metric title={industry === "Real Estate" ? "Average opportunity" : "Average order"} value={money(analytics.averageOrder, true)} copy={metricCopy} icon={<ShoppingBag />} tone="orange" /><Metric title="Repeat customers" value={`${analytics.repeatCustomers}%`} copy={metricCopy} icon={<Users />} tone="brown" /><Metric title="AI resolution" value={demoWorkspaceDataEnabled ? "94%" : "0%"} copy={metricCopy} icon={<Sparkles />} tone="rose" /></div>
    <div className="grid analytics-main-grid"><Card className="chart-box"><SectionTitle title={industry === "Real Estate" ? "Pipeline movement" : "Revenue over time"} action={<span>{range}</span>} /><div className="rechart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={analytics.revenueSeries}><defs><linearGradient id="revenueFill" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#15803d" stopOpacity={0.24}/><stop offset="95%" stopColor="#15803d" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e8eee8" /><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={10} /><YAxis tickLine={false} axisLine={false} fontSize={10} tickFormatter={(value) => money(Number(value), true)} /><Tooltip formatter={(value) => money(Number(value))} /><Area type="monotone" dataKey="revenue" stroke="#15803d" strokeWidth={2.4} fill="url(#revenueFill)" /></AreaChart></ResponsiveContainer></div></Card><Card className="chart-box"><SectionTitle title="Acquisition" /><div className="pie-chart-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={analytics.acquisition} innerRadius={58} outerRadius={82} paddingAngle={4} dataKey="value">{analytics.acquisition.map((entry, index) => <Cell key={entry.name} fill={colors[index % colors.length]} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer><div className="pie-center"><strong>{analytics.leads}</strong><span>new leads</span></div></div><div className="legend">{analytics.acquisition.map((item, index) => <span key={item.name}><i style={{ background: colors[index] }} />{item.name} {item.value}%</span>)}</div></Card></div>
    <div className="grid analytics-secondary-grid"><Card className="chart-box"><SectionTitle title="Orders and operations" /><div className="rechart-wrap small"><ResponsiveContainer width="100%" height="100%"><BarChart data={analytics.revenueSeries}><CartesianGrid vertical={false} stroke="#e8eee8" /><XAxis dataKey="label" tickLine={false} axisLine={false} fontSize={10} /><YAxis tickLine={false} axisLine={false} fontSize={10} /><Tooltip /><Bar dataKey="orders" fill="#73ad80" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer></div></Card>{demoWorkspaceDataEnabled ? <><Card><SectionTitle title="Marketing & support" /><div className="analytics-list"><div><span className="kpi-icon green"><TrendingUp /></span><div><strong>Qualified reach improved 21%</strong><p>Educational content is attracting a more relevant audience.</p></div></div><div><span className="kpi-icon orange"><MessageCircle /></span><div><strong>Median response time is 48 seconds</strong><p>AI Support resolved 94% without escalation.</p></div></div></div></Card><Card className="recommendation"><SectionTitle title="AI analysis" action={<Sparkles />} /><div className="recommendation-item"><div className="eyebrow">What happened?</div><div className="rec-title">{industry === "Real Estate" ? "Qualified pipeline increased as buyer saves and viewing requests accelerated." : "Revenue increased 18%, led by repeat demand for Fresh Eggs."}</div></div><div className="recommendation-item"><div className="eyebrow">Why?</div><div className="rec-copy">Faster responses and better-performing educational content are increasing qualified activity.</div></div><div className="recommendation-item"><div className="eyebrow">Recommended action</div><div className="rec-copy">Prioritize the warmest audience before broadening reach.</div><Button variant="green" className="btn-sm" onClick={() => setLocation("/opportunities")}>Review opportunities</Button></div></Card></> : <Card className="recommendation"><SectionTitle title="AI analysis" action={<Sparkles />} /><div className="empty compact-empty"><BarChart3 /><h3>No analysis yet</h3><p>Connect a supported analytics API to populate this workspace.</p></div></Card>}</div>
  </>;
}
