from __future__ import annotations

import base64
from dataclasses import dataclass
from io import BytesIO
from typing import Literal, Protocol, runtime_checkable
from uuid import UUID, uuid4

from openai import AsyncOpenAI, OpenAIError
from PIL import Image, UnidentifiedImageError

from app.core.config import Settings
from app.storage.base import ObjectStorage, StorageError


DEFAULT_OPENAI_IMAGE_MODEL = "gpt-image-2"
DEFAULT_CREATIVE_QUALITY: Literal["low", "medium", "high", "auto"] = "medium"

_MAX_GENERATED_IMAGE_BYTES = 30 * 1024 * 1024
_MAX_PUBLIC_REFERENCE_LENGTH = 1024

# GPT-Image-2 current Image API constraints.
_MIN_IMAGE_PIXELS = 655_360
_MAX_IMAGE_PIXELS = 8_294_400
_MAX_IMAGE_EDGE = 3840
_MAX_EDGE_RATIO = 3.0


@dataclass(frozen=True, slots=True)
class CreativeGenerationRequest:
    """
    Provider-neutral request for an internal draft creative.

    The generated provider asset is deliberately only the visual layer.
    Exact brand marks, marketing copy, CTA text, and other deterministic
    overlays are composed by the application in a later stage.
    """

    business_id: UUID
    creative_asset_id: UUID
    instructions: str
    width: int | None
    height: int | None
    aspect_ratio: str | None

    def __post_init__(self) -> None:
        instructions = self.instructions.strip()
        if not instructions or len(instructions) > 5000:
            raise ValueError("instructions must contain 1 to 5000 characters")

        if (self.width is None) != (self.height is None):
            raise ValueError("width and height must be supplied together")

        if self.width is not None and not 1 <= self.width <= 20000:
            raise ValueError("width must be between 1 and 20000")

        if self.height is not None and not 1 <= self.height <= 20000:
            raise ValueError("height must be between 1 and 20000")

        if self.aspect_ratio is not None:
            ratio = self.aspect_ratio.strip()
            if not ratio or len(ratio) > 16:
                raise ValueError("aspect_ratio must contain 1 to 16 characters")


@dataclass(frozen=True, slots=True)
class CreativeGenerationResult:
    """Safe reference result; binary asset bytes never enter PostgreSQL."""

    storage_reference: str
    width: int
    height: int
    provider_request_id: str | None = None


@runtime_checkable
class CreativeGenerationProvider(Protocol):
    @property
    def provider_name(self) -> str: ...

    async def generate_draft(
        self,
        request: CreativeGenerationRequest,
    ) -> CreativeGenerationResult: ...


class CreativeProviderError(RuntimeError):
    """Safe base error for creative-generation failures."""


class CreativeProviderNotConfiguredError(CreativeProviderError):
    pass


class CreativeProviderGenerationError(CreativeProviderError):
    """The external image provider could not return a usable draft."""


class CreativeProviderInvalidOutputError(CreativeProviderError):
    """The provider returned malformed or unsafe image output."""


class CreativeProviderStorageError(CreativeProviderError):
    """Generated bytes could not be persisted safely."""


class UnavailableCreativeGenerationProvider:
    """Intentional default: disabled creative generation is explicit and testable."""

    provider_name = "unconfigured"

    async def generate_draft(
        self,
        request: CreativeGenerationRequest,
    ) -> CreativeGenerationResult:
        del request
        raise CreativeProviderNotConfiguredError(
            "Creative generation provider is not configured"
        )


class OpenAICreativeGenerationProvider:
    """
    Production GPT-Image provider for raw marketing visual generation.

    Responsibilities:
    - call the server-side OpenAI Image API;
    - prohibit generated overlay copy / invented branding in the prompt;
    - decode and validate returned image bytes;
    - persist bytes through the existing ObjectStorage abstraction;
    - return only a safe public storage reference and verified dimensions.

    It intentionally does NOT compose the final logo, headline, CTA, or other
    precise brand elements. Those belong to the deterministic composition layer.
    """

    provider_name = "openai"

    def __init__(
        self,
        *,
        client: AsyncOpenAI,
        storage: ObjectStorage,
        model: str = DEFAULT_OPENAI_IMAGE_MODEL,
        quality: Literal["low", "medium", "high", "auto"] = DEFAULT_CREATIVE_QUALITY,
    ) -> None:
        normalized_model = model.strip()
        if not normalized_model:
            raise ValueError("Creative image model cannot be blank")

        self.client = client
        self.storage = storage
        self.model = normalized_model
        self.quality = quality

    async def generate_draft(
        self,
        request: CreativeGenerationRequest,
    ) -> CreativeGenerationResult:
        size = _resolve_generation_size(request)
        prompt = _build_visual_prompt(request)

        try:
            response = await self.client.images.generate(
                model=self.model,
                prompt=prompt,
                size=size,
                quality=self.quality,
                n=1,
            )
        except OpenAIError:
            raise CreativeProviderGenerationError(
                "Creative image provider could not complete the request"
            ) from None

        encoded = _extract_base64_image(response)
        image_bytes = _decode_image(encoded)
        width, height = _validate_generated_png(image_bytes)

        object_key = _creative_storage_key(
            business_id=request.business_id,
            creative_asset_id=request.creative_asset_id,
        )

        try:
            public_reference = self.storage.public_url(object_key)
            if (
                not public_reference
                or len(public_reference) > _MAX_PUBLIC_REFERENCE_LENGTH
            ):
                raise CreativeProviderStorageError(
                    "Generated creative storage reference is invalid"
                )

            await self.storage.put(
                object_key,
                image_bytes,
                "image/png",
            )
        except CreativeProviderStorageError:
            raise
        except StorageError:
            raise CreativeProviderStorageError(
                "Generated creative could not be stored"
            ) from None

        request_id = getattr(response, "_request_id", None)
        if not isinstance(request_id, str) or not request_id.strip():
            request_id = None

        return CreativeGenerationResult(
            storage_reference=public_reference,
            width=width,
            height=height,
            provider_request_id=request_id,
        )


def _build_visual_prompt(request: CreativeGenerationRequest) -> str:
    return (
        "Create one polished commercial marketing VISUAL LAYER based only on "
        "the following authorized creative direction.\n\n"
        f"{request.instructions.strip()}\n\n"
        "Important production constraints:\n"
        "- Generate the photographic, illustrative, environmental, product-scene, "
        "or abstract visual only.\n"
        "- Do not render logos, brand marks, watermarks, UI chrome, captions, "
        "headlines, CTA text, typography, letters, or invented packaging copy.\n"
        "- Do not invent certifications, awards, prices, claims, testimonials, "
        "people, products, or business facts not present in the creative direction.\n"
        "- Keep useful negative space for a later deterministic brand composition layer.\n"
        "- The application will place the real logo and exact marketing copy afterward."
    )


def _resolve_generation_size(request: CreativeGenerationRequest) -> str:
    if request.width is not None and request.height is not None:
        target_width = request.width
        target_height = request.height
    elif request.aspect_ratio:
        target_width, target_height = _dimensions_from_ratio(request.aspect_ratio)
    else:
        return "1024x1024"

    width, height = _normalize_image_api_dimensions(
        target_width,
        target_height,
    )
    return f"{width}x{height}"


def _dimensions_from_ratio(value: str) -> tuple[int, int]:
    normalized = value.strip()

    try:
        left, right = normalized.split(":", 1)
        ratio_width = float(left)
        ratio_height = float(right)
    except (ValueError, TypeError):
        raise ValueError("aspect_ratio must use WIDTH:HEIGHT format") from None

    if ratio_width <= 0 or ratio_height <= 0:
        raise ValueError("aspect_ratio values must be positive")

    ratio = ratio_width / ratio_height
    if ratio > _MAX_EDGE_RATIO or ratio < 1 / _MAX_EDGE_RATIO:
        raise ValueError("aspect_ratio exceeds the image provider limit")

    short_edge = 1024

    if ratio >= 1:
        width = round((short_edge * ratio) / 16) * 16
        height = short_edge
    else:
        width = short_edge
        height = round((short_edge / ratio) / 16) * 16

    return width, height


def _normalize_image_api_dimensions(
    width: int,
    height: int,
) -> tuple[int, int]:
    if width <= 0 or height <= 0:
        raise ValueError("creative dimensions must be positive")

    ratio = max(width, height) / min(width, height)
    if ratio > _MAX_EDGE_RATIO:
        raise ValueError("creative dimensions exceed the image provider aspect limit")

    normalized_width = max(16, round(width / 16) * 16)
    normalized_height = max(16, round(height / 16) * 16)

    longest = max(normalized_width, normalized_height)
    if longest > _MAX_IMAGE_EDGE:
        scale = _MAX_IMAGE_EDGE / longest
        normalized_width = max(
            16,
            int((normalized_width * scale) // 16) * 16,
        )
        normalized_height = max(
            16,
            int((normalized_height * scale) // 16) * 16,
        )

    pixels = normalized_width * normalized_height

    if pixels < _MIN_IMAGE_PIXELS:
        scale = (_MIN_IMAGE_PIXELS / pixels) ** 0.5
        normalized_width = max(
            16,
            round((normalized_width * scale) / 16) * 16,
        )
        normalized_height = max(
            16,
            round((normalized_height * scale) / 16) * 16,
        )

    pixels = normalized_width * normalized_height
    if pixels > _MAX_IMAGE_PIXELS:
        scale = (_MAX_IMAGE_PIXELS / pixels) ** 0.5
        normalized_width = max(
            16,
            int((normalized_width * scale) // 16) * 16,
        )
        normalized_height = max(
            16,
            int((normalized_height * scale) // 16) * 16,
        )

    if (
        normalized_width > _MAX_IMAGE_EDGE
        or normalized_height > _MAX_IMAGE_EDGE
        or normalized_width % 16
        or normalized_height % 16
    ):
        raise ValueError("creative dimensions cannot be normalized safely")

    pixels = normalized_width * normalized_height
    if not _MIN_IMAGE_PIXELS <= pixels <= _MAX_IMAGE_PIXELS:
        raise ValueError("creative dimensions are outside image provider limits")

    return normalized_width, normalized_height


def _extract_base64_image(response: object) -> str:
    data = getattr(response, "data", None)

    if not isinstance(data, list) or not data:
        raise CreativeProviderInvalidOutputError(
            "Creative image provider returned no image"
        )

    encoded = getattr(data[0], "b64_json", None)

    if not isinstance(encoded, str) or not encoded:
        raise CreativeProviderInvalidOutputError(
            "Creative image provider returned invalid image data"
        )

    return encoded


def _decode_image(encoded: str) -> bytes:
    try:
        content = base64.b64decode(encoded, validate=True)
    except (ValueError, TypeError):
        raise CreativeProviderInvalidOutputError(
            "Creative image provider returned malformed image data"
        ) from None

    if not content or len(content) > _MAX_GENERATED_IMAGE_BYTES:
        raise CreativeProviderInvalidOutputError(
            "Creative image provider returned an invalid image size"
        )

    return content


def _validate_generated_png(content: bytes) -> tuple[int, int]:
    try:
        with Image.open(BytesIO(content)) as image:
            width, height = image.size
            image_format = image.format
            image.verify()
    except (UnidentifiedImageError, OSError, ValueError):
        raise CreativeProviderInvalidOutputError(
            "Creative image provider returned an unreadable image"
        ) from None

    if image_format != "PNG":
        raise CreativeProviderInvalidOutputError(
            "Creative image provider returned an unexpected image format"
        )

    if (
        width < 1
        or height < 1
        or width > _MAX_IMAGE_EDGE
        or height > _MAX_IMAGE_EDGE
        or width * height > _MAX_IMAGE_PIXELS
    ):
        raise CreativeProviderInvalidOutputError(
            "Creative image provider returned unsupported dimensions"
        )

    return width, height


def _creative_storage_key(
    *,
    business_id: UUID,
    creative_asset_id: UUID,
) -> str:
    return (
        f"businesses/{business_id}/marketing/creatives/"
        f"{creative_asset_id}/{uuid4().hex}.png"
    )


def create_creative_generation_provider(
    config: Settings,
    storage: ObjectStorage,
) -> CreativeGenerationProvider:
    """
    Build the production image provider from backend-only configuration.

    Unlike the text-agent dependency, absence of an API key intentionally
    returns an explicit unavailable provider. This lets the marketing service
    persist generation_status='provider_required' rather than losing that
    truthful state to an HTTP transaction rollback.
    """
    api_key = config.openai_api_key_value

    if api_key is None or not api_key.strip():
        return UnavailableCreativeGenerationProvider()

    client = AsyncOpenAI(
        api_key=api_key,
        timeout=config.openai_timeout_seconds,
        max_retries=config.openai_max_retries,
    )

    return OpenAICreativeGenerationProvider(
        client=client,
        storage=storage,
        model=config.openai_image_model,
        quality=config.openai_image_quality,
    )
