"""add phase two ad commerce execution

Revision ID: 11ec1b452f69
Revises: 0991074b3c9e
Create Date: 2026-08-26 15:44:25.226634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11ec1b452f69'
down_revision: Union[str, Sequence[str], None] = '0991074b3c9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commerce_product_groups',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('external_key', sa.String(length=160), nullable=False),
    sa.Column('group_type', sa.String(length=32), nullable=False),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='draft', nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("group_type IN ('manual','category','collection','brand','tag','price','margin','best_sellers','new_products','promotion','custom_rule')", name=op.f('ck_commerce_product_groups_valid_group_type')),
    sa.CheckConstraint("jsonb_typeof(rule) = 'object' AND pg_column_size(rule) <= 16384", name=op.f('ck_commerce_product_groups_valid_rule')),
    sa.CheckConstraint("status IN ('draft','active','archived')", name=op.f('ck_commerce_product_groups_valid_status')),
    sa.CheckConstraint('char_length(btrim(name)) BETWEEN 1 AND 160', name=op.f('ck_commerce_product_groups_valid_name')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_commerce_product_groups_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_commerce_product_groups_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commerce_product_groups')),
    sa.UniqueConstraint('business_id', 'external_key', name='uq_commerce_product_groups_external_key'),
    sa.UniqueConstraint('id', 'business_id', name='uq_commerce_product_groups_id_business')
    )
    op.create_index('ix_commerce_product_groups_business_status', 'commerce_product_groups', ['business_id', 'status', 'id'], unique=False)
    op.create_table('commerce_product_group_items',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('product_group_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_commerce_product_group_items_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['catalog_item_id', 'business_id'], ['catalog_items.id', 'catalog_items.business_id'], name='fk_product_group_items_item_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_group_id', 'business_id'], ['commerce_product_groups.id', 'commerce_product_groups.business_id'], name='fk_product_group_items_group_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commerce_product_group_items')),
    sa.UniqueConstraint('business_id', 'product_group_id', 'catalog_item_id', name='uq_product_group_items_group_item')
    )
    op.create_index('ix_product_group_items_business_item', 'commerce_product_group_items', ['business_id', 'catalog_item_id', 'product_group_id'], unique=False)
    op.create_table('commerce_product_group_destinations',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('product_group_id', sa.Uuid(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending','submitted','ready','attention_required','archived')", name=op.f('ck_commerce_product_group_destinations_valid_status')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_commerce_product_group_destinations_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['destination_id', 'business_id'], ['commerce_feed_destinations.id', 'commerce_feed_destinations.business_id'], name='fk_product_group_destinations_destination_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_group_id', 'business_id'], ['commerce_product_groups.id', 'commerce_product_groups.business_id'], name='fk_product_group_destinations_group_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_commerce_product_group_destinations')),
    sa.UniqueConstraint('business_id', 'product_group_id', 'destination_id', name='uq_product_group_destinations_group_destination')
    )
    op.create_table('external_campaign_deployments',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('integration_connection_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('external_campaign_reference', sa.String(length=255), nullable=True),
    sa.Column('child_references', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='executing', nullable=False),
    sa.Column('safe_payload_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('provider_status', sa.String(length=64), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('last_reconciled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(child_references) = 'object' AND pg_column_size(child_references) <= 16384", name=op.f('ck_external_campaign_deployments_valid_child_references')),
    sa.CheckConstraint("provider IN ('google','meta')", name=op.f('ck_external_campaign_deployments_valid_provider')),
    sa.CheckConstraint("status IN ('executing','provider_pending','active','paused','completed','failed','attention_required','unknown_external_state')", name=op.f('ck_external_campaign_deployments_valid_status')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_external_campaign_deployments_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id', 'business_id'], ['marketing_campaigns.id', 'marketing_campaigns.business_id'], name='fk_external_campaign_deployments_campaign_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['integration_connection_id', 'business_id'], ['integration_connections.id', 'integration_connections.business_id'], name='fk_external_campaign_deployments_connection_business'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_campaign_deployments')),
    sa.UniqueConstraint('business_id', 'campaign_id', 'provider', name='uq_external_campaign_deployments_campaign_provider'),
    sa.UniqueConstraint('id', 'business_id', name='uq_external_campaign_deployments_id_business'),
    sa.UniqueConstraint('integration_connection_id', 'external_campaign_reference', name='uq_external_campaign_deployments_connection_external')
    )
    op.create_index('ix_external_campaign_deployments_business_status', 'external_campaign_deployments', ['business_id', 'status', 'provider', 'id'], unique=False)
    op.create_table('product_campaign_performance',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('campaign_id', sa.Uuid(), nullable=False),
    sa.Column('catalog_item_id', sa.Uuid(), nullable=False),
    sa.Column('product_group_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('external_campaign_reference', sa.String(length=255), nullable=False),
    sa.Column('external_product_reference', sa.String(length=255), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('spend', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('impressions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('clicks', sa.Integer(), server_default='0', nullable=False),
    sa.Column('conversions', sa.Numeric(precision=14, scale=4), server_default='0', nullable=False),
    sa.Column('conversion_value', sa.Numeric(precision=14, scale=2), server_default='0', nullable=False),
    sa.Column('attribution_class', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("attribution_class IN ('provider_attributed','first_party_observed','ai_business_os_derived','unknown')", name=op.f('ck_product_campaign_performance_valid_attribution_class')),
    sa.CheckConstraint("provider IN ('google','meta')", name=op.f('ck_product_campaign_performance_valid_provider')),
    sa.CheckConstraint('period_end >= period_start', name=op.f('ck_product_campaign_performance_valid_period')),
    sa.CheckConstraint('spend >= 0 AND impressions >= 0 AND clicks >= 0 AND conversions >= 0 AND conversion_value >= 0', name=op.f('ck_product_campaign_performance_valid_metrics')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_product_campaign_performance_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id', 'business_id'], ['marketing_campaigns.id', 'marketing_campaigns.business_id'], name='fk_product_campaign_performance_campaign_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['catalog_item_id', 'business_id'], ['catalog_items.id', 'catalog_items.business_id'], name='fk_product_campaign_performance_item_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_group_id'], ['commerce_product_groups.id'], name=op.f('fk_product_campaign_performance_product_group_id_commerce_product_groups'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_campaign_performance')),
    sa.UniqueConstraint('business_id', 'campaign_id', 'catalog_item_id', 'provider', 'period_start', 'period_end', 'attribution_class', name='uq_product_campaign_performance_slice')
    )
    op.create_index('ix_product_campaign_performance_business_campaign', 'product_campaign_performance', ['business_id', 'campaign_id', 'period_start', 'id'], unique=False)
    op.add_column('commerce_feed_destinations', sa.Column('integration_connection_id', sa.Uuid(), nullable=True))
    op.add_column('commerce_feed_destinations', sa.Column('external_resource_id', sa.String(length=512), nullable=True))
    op.add_column('commerce_feed_destinations', sa.Column('managed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('commerce_feed_destinations', sa.Column('content_language', sa.String(length=16), server_default='en', nullable=False))
    op.add_column('commerce_feed_destinations', sa.Column('feed_label', sa.String(length=20), nullable=True))
    op.add_column('commerce_feed_destinations', sa.Column('submitted_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('commerce_feed_destinations', sa.Column('limited_count', sa.Integer(), server_default='0', nullable=False))
    op.drop_constraint(op.f('ck_commerce_feed_destinations_valid_counts'), 'commerce_feed_destinations', type_='check')
    op.create_check_constraint(
        op.f('ck_commerce_feed_destinations_valid_counts'), 'commerce_feed_destinations',
        'eligible_count >= 0 AND warning_count >= 0 AND rejected_count >= 0 AND '
        'synchronized_count >= 0 AND submitted_count >= 0 AND limited_count >= 0',
    )
    op.create_foreign_key('fk_feed_destinations_integration_business', 'commerce_feed_destinations', 'integration_connections', ['integration_connection_id', 'business_id'], ['id', 'business_id'])
    op.add_column('commerce_feed_product_statuses', sa.Column('provider_issues', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False))
    op.add_column('commerce_feed_product_statuses', sa.Column('owned_by_aibos', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('commerce_feed_product_statuses', sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_constraint(op.f('ck_commerce_feed_product_statuses_valid_status'), 'commerce_feed_product_statuses', type_='check')
    op.create_check_constraint(
        op.f('ck_commerce_feed_product_statuses_valid_status'), 'commerce_feed_product_statuses',
        "status IN ('attention_required','pending','submitted','processing','eligible','limited',"
        "'warning','ineligible','rejected','error','archived','removed')",
    )
    op.add_column('marketing_campaigns', sa.Column('normalized_proposal', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False))
    op.add_column('marketing_campaigns', sa.Column('recommended_provider', sa.String(length=24), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('campaign_type', sa.String(length=48), nullable=True))
    op.add_column('marketing_campaigns', sa.Column('offer_source', sa.String(length=32), server_default='none', nullable=False))
    op.add_column('marketing_campaigns', sa.Column('offer_authorized', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('marketing_campaigns', sa.Column('proposal_confidence', sa.Numeric(precision=4, scale=3), nullable=True))
    op.drop_constraint(op.f('ck_marketing_campaigns_valid_status'), 'marketing_campaigns', type_='check')
    op.create_check_constraint(
        op.f('ck_marketing_campaigns_valid_status'), 'marketing_campaigns',
        "status IN ('draft','planned','awaiting_approval','approved','scheduled','executing',"
        "'provider_pending','active','paused','completed','canceled','failed',"
        "'attention_required','unknown_external_state')",
    )
    op.add_column('background_jobs', sa.Column('commerce_feed_destination_id', sa.Uuid(), nullable=True))
    op.add_column('background_jobs', sa.Column('marketing_campaign_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_jobs_commerce_feed_destination_business', 'background_jobs',
        'commerce_feed_destinations', ['commerce_feed_destination_id', 'business_id'],
        ['id', 'business_id'], ondelete='CASCADE',
    )
    op.create_foreign_key(
        'fk_jobs_marketing_campaign_business', 'background_jobs',
        'marketing_campaigns', ['marketing_campaign_id', 'business_id'],
        ['id', 'business_id'], ondelete='CASCADE',
    )
    op.drop_constraint(op.f('ck_background_jobs_valid_job_type'), 'background_jobs', type_='check')
    op.create_check_constraint(
        op.f('ck_background_jobs_valid_job_type'), 'background_jobs',
        "job_type IN ('process_automation_event','resume_workflow_run',"
        "'process_scheduled_workflow','process_integration_event','dispatch_action_execution',"
        "'reconcile_uncertain_attempt','mark_social_schedule_ready','maintain_subscription',"
        "'discover_competitors','generate_content_plan','analyze_campaign_opportunities',"
        "'commerce_initial_sync','commerce_incremental_sync','commerce_webhook_reconcile',"
        "'google_merchant_status_sync','meta_catalog_status_sync',"
        "'google_ads_performance_sync','meta_ads_performance_sync')",
    )
    op.add_column('marketing_performance', sa.Column('attribution_class', sa.String(length=32), server_default='unknown', nullable=False))
    op.add_column('marketing_performance', sa.Column('external_campaign_reference', sa.String(length=255), nullable=True))
    op.create_check_constraint(
        op.f('ck_marketing_performance_valid_attribution_class'), 'marketing_performance',
        "attribution_class IN ('provider_attributed','first_party_observed','ai_business_os_derived','unknown')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_marketing_performance_valid_attribution_class'), 'marketing_performance', type_='check')
    op.drop_column('marketing_performance', 'external_campaign_reference')
    op.drop_column('marketing_performance', 'attribution_class')
    op.execute("DELETE FROM background_jobs WHERE job_type IN ('google_merchant_status_sync','meta_catalog_status_sync','google_ads_performance_sync','meta_ads_performance_sync')")
    op.drop_constraint(op.f('ck_background_jobs_valid_job_type'), 'background_jobs', type_='check')
    op.create_check_constraint(
        op.f('ck_background_jobs_valid_job_type'), 'background_jobs',
        "job_type IN ('process_automation_event','resume_workflow_run',"
        "'process_scheduled_workflow','process_integration_event','dispatch_action_execution',"
        "'reconcile_uncertain_attempt','mark_social_schedule_ready','maintain_subscription',"
        "'discover_competitors','generate_content_plan','analyze_campaign_opportunities',"
        "'commerce_initial_sync','commerce_incremental_sync','commerce_webhook_reconcile')",
    )
    op.drop_constraint('fk_jobs_marketing_campaign_business', 'background_jobs', type_='foreignkey')
    op.drop_constraint('fk_jobs_commerce_feed_destination_business', 'background_jobs', type_='foreignkey')
    op.drop_column('background_jobs', 'marketing_campaign_id')
    op.drop_column('background_jobs', 'commerce_feed_destination_id')
    op.execute("UPDATE marketing_campaigns SET status = 'paused' WHERE status IN ('executing','provider_pending','attention_required','unknown_external_state')")
    op.execute("UPDATE marketing_campaigns SET status = 'canceled' WHERE status = 'failed'")
    op.drop_constraint(op.f('ck_marketing_campaigns_valid_status'), 'marketing_campaigns', type_='check')
    op.create_check_constraint(
        op.f('ck_marketing_campaigns_valid_status'), 'marketing_campaigns',
        "status IN ('draft','planned','awaiting_approval','approved','scheduled','active','paused','completed','canceled')",
    )
    op.drop_column('marketing_campaigns', 'proposal_confidence')
    op.drop_column('marketing_campaigns', 'offer_authorized')
    op.drop_column('marketing_campaigns', 'offer_source')
    op.drop_column('marketing_campaigns', 'campaign_type')
    op.drop_column('marketing_campaigns', 'recommended_provider')
    op.drop_column('marketing_campaigns', 'normalized_proposal')
    op.execute("UPDATE commerce_feed_product_statuses SET status = CASE WHEN status IN ('submitted','processing') THEN 'pending' WHEN status = 'limited' THEN 'warning' WHEN status IN ('attention_required','ineligible','error') THEN 'rejected' WHEN status = 'archived' THEN 'removed' ELSE status END")
    op.drop_constraint(op.f('ck_commerce_feed_product_statuses_valid_status'), 'commerce_feed_product_statuses', type_='check')
    op.create_check_constraint(
        op.f('ck_commerce_feed_product_statuses_valid_status'), 'commerce_feed_product_statuses',
        "status IN ('pending','eligible','warning','rejected','removed')",
    )
    op.drop_column('commerce_feed_product_statuses', 'submitted_at')
    op.drop_column('commerce_feed_product_statuses', 'owned_by_aibos')
    op.drop_column('commerce_feed_product_statuses', 'provider_issues')
    op.drop_constraint('fk_feed_destinations_integration_business', 'commerce_feed_destinations', type_='foreignkey')
    op.drop_constraint(op.f('ck_commerce_feed_destinations_valid_counts'), 'commerce_feed_destinations', type_='check')
    op.create_check_constraint(
        op.f('ck_commerce_feed_destinations_valid_counts'), 'commerce_feed_destinations',
        'eligible_count >= 0 AND warning_count >= 0 AND rejected_count >= 0 AND synchronized_count >= 0',
    )
    op.drop_column('commerce_feed_destinations', 'limited_count')
    op.drop_column('commerce_feed_destinations', 'submitted_count')
    op.drop_column('commerce_feed_destinations', 'feed_label')
    op.drop_column('commerce_feed_destinations', 'content_language')
    op.drop_column('commerce_feed_destinations', 'managed')
    op.drop_column('commerce_feed_destinations', 'external_resource_id')
    op.drop_column('commerce_feed_destinations', 'integration_connection_id')
    op.drop_index('ix_product_campaign_performance_business_campaign', table_name='product_campaign_performance')
    op.drop_table('product_campaign_performance')
    op.drop_index('ix_external_campaign_deployments_business_status', table_name='external_campaign_deployments')
    op.drop_table('external_campaign_deployments')
    op.drop_table('commerce_product_group_destinations')
    op.drop_index('ix_product_group_items_business_item', table_name='commerce_product_group_items')
    op.drop_table('commerce_product_group_items')
    op.drop_index('ix_commerce_product_groups_business_status', table_name='commerce_product_groups')
    op.drop_table('commerce_product_groups')
    # ### end Alembic commands ###
