"""add ai agent execution ledger

Revision ID: 34cf6a541b22
Revises: 71ff35af83b6
Create Date: 2026-08-22 00:13:23.622397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34cf6a541b22'
down_revision: Union[str, Sequence[str], None] = '71ff35af83b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_agent_executions',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('trigger_type', sa.String(length=16), server_default='api', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='running', nullable=False),
    sa.Column('task', sa.Text(), nullable=False),
    sa.Column('provider_name', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('context_revision', sa.String(length=64), nullable=True),
    sa.Column('context_source_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('business_brain_source_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('memory_source_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('output_summary', sa.Text(), nullable=True),
    sa.Column('recommendations', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('proposed_actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('provider_request_id', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('input_tokens', sa.BigInteger(), nullable=True),
    sa.Column('output_tokens', sa.BigInteger(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'running' AND completed_at IS NULL) OR (status <> 'running' AND completed_at IS NOT NULL)", name=op.f('ck_ai_agent_executions_valid_completion_state')),
    sa.CheckConstraint("context_revision IS NULL OR (char_length(context_revision) = 64 AND context_revision = lower(context_revision) AND context_revision ~ '^[0-9a-f]{64}$')", name=op.f('ck_ai_agent_executions_valid_context_revision')),
    sa.CheckConstraint("role IN ('business_manager', 'cmo', 'sales', 'support', 'operations', 'analytics')", name=op.f('ck_ai_agent_executions_valid_role')),
    sa.CheckConstraint("status IN ('running', 'completed', 'needs_approval', 'blocked', 'failed')", name=op.f('ck_ai_agent_executions_valid_status')),
    sa.CheckConstraint("trigger_type IN ('api', 'automation', 'system')", name=op.f('ck_ai_agent_executions_valid_trigger_type')),
    sa.CheckConstraint('business_brain_source_count + memory_source_count = context_source_count', name=op.f('ck_ai_agent_executions_consistent_context_source_counts')),
    sa.CheckConstraint('business_brain_source_count >= 0', name=op.f('ck_ai_agent_executions_valid_business_brain_source_count')),
    sa.CheckConstraint('char_length(btrim(model_name)) BETWEEN 1 AND 128', name=op.f('ck_ai_agent_executions_valid_model_name')),
    sa.CheckConstraint('char_length(btrim(provider_name)) BETWEEN 1 AND 64', name=op.f('ck_ai_agent_executions_valid_provider_name')),
    sa.CheckConstraint('char_length(btrim(task)) BETWEEN 1 AND 4000', name=op.f('ck_ai_agent_executions_valid_task')),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= created_at', name=op.f('ck_ai_agent_executions_valid_completed_at')),
    sa.CheckConstraint('context_source_count >= 0', name=op.f('ck_ai_agent_executions_valid_context_source_count')),
    sa.CheckConstraint('duration_ms IS NULL OR duration_ms >= 0', name=op.f('ck_ai_agent_executions_valid_duration_ms')),
    sa.CheckConstraint('estimated_cost_usd IS NULL OR estimated_cost_usd >= 0', name=op.f('ck_ai_agent_executions_valid_estimated_cost_usd')),
    sa.CheckConstraint('failure_code IS NULL OR char_length(btrim(failure_code)) BETWEEN 1 AND 64', name=op.f('ck_ai_agent_executions_valid_failure_code')),
    sa.CheckConstraint('input_tokens IS NULL OR input_tokens >= 0', name=op.f('ck_ai_agent_executions_valid_input_tokens')),
    sa.CheckConstraint('memory_source_count >= 0', name=op.f('ck_ai_agent_executions_valid_memory_source_count')),
    sa.CheckConstraint('output_summary IS NULL OR char_length(btrim(output_summary)) BETWEEN 1 AND 12000', name=op.f('ck_ai_agent_executions_valid_output_summary')),
    sa.CheckConstraint('output_tokens IS NULL OR output_tokens >= 0', name=op.f('ck_ai_agent_executions_valid_output_tokens')),
    sa.CheckConstraint('provider_request_id IS NULL OR char_length(btrim(provider_request_id)) BETWEEN 1 AND 255', name=op.f('ck_ai_agent_executions_valid_provider_request_id')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_ai_agent_executions_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_ai_agent_executions_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_agent_executions'))
    )
    op.create_index('ix_ai_agent_executions_business_created', 'ai_agent_executions', ['business_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_ai_agent_executions_business_role_created', 'ai_agent_executions', ['business_id', 'role', 'created_at', 'id'], unique=False)
    op.create_index('ix_ai_agent_executions_business_status_created', 'ai_agent_executions', ['business_id', 'status', 'created_at', 'id'], unique=False)
    op.create_index('ix_ai_agent_executions_requester_created', 'ai_agent_executions', ['requested_by_user_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_agent_executions_requester_created', table_name='ai_agent_executions')
    op.drop_index('ix_ai_agent_executions_business_status_created', table_name='ai_agent_executions')
    op.drop_index('ix_ai_agent_executions_business_role_created', table_name='ai_agent_executions')
    op.drop_index('ix_ai_agent_executions_business_created', table_name='ai_agent_executions')
    op.drop_table('ai_agent_executions')
    # ### end Alembic commands ###
