"""link ai executions to opportunities

Revision ID: 6b6dc1e42c48
Revises: c13d4e5f6a70
Create Date: 2026-08-27 15:40:00.230982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b6dc1e42c48'
down_revision: Union[str, Sequence[str], None] = 'c13d4e5f6a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_agent_executions', sa.Column('opportunity_id', sa.Uuid(), nullable=True))
    op.create_index('ix_ai_agent_executions_business_opportunity_created', 'ai_agent_executions', ['business_id', 'opportunity_id', 'created_at', 'id'], unique=False)
    op.create_foreign_key('fk_ai_agent_executions_opportunity_business', 'ai_agent_executions', 'opportunities', ['opportunity_id', 'business_id'], ['id', 'business_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_ai_agent_executions_opportunity_business', 'ai_agent_executions', type_='foreignkey')
    op.drop_index('ix_ai_agent_executions_business_opportunity_created', table_name='ai_agent_executions')
    op.drop_column('ai_agent_executions', 'opportunity_id')
    # ### end Alembic commands ###
