"""add persistent business memory

Revision ID: 71ff35af83b6
Revises: b3e7d1a42c90
Create Date: 2026-08-20 23:25:43.913762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71ff35af83b6'
down_revision: Union[str, Sequence[str], None] = 'b3e7d1a42c90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_memories',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('memory_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='active', nullable=False),
    sa.Column('importance', sa.Integer(), server_default='3', nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), server_default='1.000', nullable=False),
    sa.Column('source_type', sa.String(length=16), server_default='manual', nullable=False),
    sa.Column('source_reference', sa.String(length=1024), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_reinforced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('superseded_by_memory_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("char_length(content_hash) = 64 AND content_hash = lower(content_hash) AND content_hash ~ '^[0-9a-f]{64}$'", name=op.f('ck_business_memories_valid_content_hash')),
    sa.CheckConstraint("memory_type IN ('episodic', 'semantic', 'procedural', 'decision', 'customer', 'ai_learning')", name=op.f('ck_business_memories_valid_memory_type')),
    sa.CheckConstraint("source_type IN ('manual', 'system')", name=op.f('ck_business_memories_valid_source_type')),
    sa.CheckConstraint("status IN ('active', 'superseded', 'archived')", name=op.f('ck_business_memories_valid_status')),
    sa.CheckConstraint('char_length(btrim(content)) BETWEEN 1 AND 10000', name=op.f('ck_business_memories_valid_content')),
    sa.CheckConstraint('confidence BETWEEN 0.000 AND 1.000', name=op.f('ck_business_memories_valid_confidence')),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name=op.f('ck_business_memories_valid_importance')),
    sa.CheckConstraint('superseded_by_memory_id IS NULL OR superseded_by_memory_id <> id', name=op.f('ck_business_memories_not_self_superseded')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_business_memories_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['superseded_by_memory_id'], ['business_memories.id'], name=op.f('fk_business_memories_superseded_by_memory_id_business_memories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_business_memories'))
    )
    op.create_index('ix_business_memories_business_content_hash', 'business_memories', ['business_id', 'content_hash'], unique=False)
    op.create_index('ix_business_memories_business_status_created', 'business_memories', ['business_id', 'status', 'created_at', 'id'], unique=False)
    op.create_index('ix_business_memories_business_type_created', 'business_memories', ['business_id', 'memory_type', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_business_memories_business_type_created', table_name='business_memories')
    op.drop_index('ix_business_memories_business_status_created', table_name='business_memories')
    op.drop_index('ix_business_memories_business_content_hash', table_name='business_memories')
    op.drop_table('business_memories')
    # ### end Alembic commands ###
