"""add durable automation engine

Revision ID: c1f8a7e4d263
Revises: b9d6f4a21573
Create Date: 2026-08-23 05:06:44.193769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1f8a7e4d263'
down_revision: Union[str, Sequence[str], None] = 'b9d6f4a21573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_events',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='pending', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(payload) = 'object'", name=op.f('ck_automation_events_valid_payload')),
    sa.CheckConstraint("status IN ('pending','processing','processed','failed')", name=op.f('ck_automation_events_valid_status')),
    sa.CheckConstraint('char_length(btrim(entity_type)) BETWEEN 1 AND 64', name=op.f('ck_automation_events_valid_entity_type')),
    sa.CheckConstraint('char_length(btrim(event_type)) BETWEEN 1 AND 64', name=op.f('ck_automation_events_valid_event_type')),
    sa.CheckConstraint('failure_code IS NULL OR char_length(btrim(failure_code)) BETWEEN 1 AND 64', name=op.f('ck_automation_events_valid_failure_code')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_automation_events_business_id_businesses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_events')),
    sa.UniqueConstraint('id', 'business_id', name='uq_automation_events_id_business')
    )
    op.create_index('ix_automation_events_business_status_occurred', 'automation_events', ['business_id', 'status', 'occurred_at', 'id'], unique=False)
    op.create_index('ix_automation_events_business_type_occurred', 'automation_events', ['business_id', 'event_type', 'occurred_at', 'id'], unique=False)
    op.create_table('automation_workflows',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default='draft', nullable=False),
    sa.Column('current_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('trigger_type', sa.String(length=64), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('timezone', sa.String(length=64), server_default='UTC', nullable=False),
    sa.Column('schedule_definition', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'active') = enabled", name=op.f('ck_automation_workflows_consistent_enabled_status')),
    sa.CheckConstraint("jsonb_typeof(schedule_definition) = 'object'", name=op.f('ck_automation_workflows_valid_schedule_definition')),
    sa.CheckConstraint("status IN ('draft','active','paused','archived')", name=op.f('ck_automation_workflows_valid_status')),
    sa.CheckConstraint('char_length(btrim(name)) BETWEEN 1 AND 180', name=op.f('ck_automation_workflows_valid_name')),
    sa.CheckConstraint('char_length(btrim(timezone)) BETWEEN 1 AND 64', name=op.f('ck_automation_workflows_valid_timezone')),
    sa.CheckConstraint('char_length(btrim(trigger_type)) BETWEEN 1 AND 64', name=op.f('ck_automation_workflows_valid_trigger_type')),
    sa.CheckConstraint('current_version >= 1', name=op.f('ck_automation_workflows_valid_current_version')),
    sa.CheckConstraint('description IS NULL OR char_length(description) <= 2000', name=op.f('ck_automation_workflows_valid_description')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_automation_workflows_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_automation_workflows_created_by_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_workflows')),
    sa.UniqueConstraint('id', 'business_id', name='uq_automation_workflows_id_business')
    )
    op.create_index('ix_automation_workflows_business_next_run', 'automation_workflows', ['business_id', 'next_run_at', 'id'], unique=False)
    op.create_index('ix_automation_workflows_business_status_updated', 'automation_workflows', ['business_id', 'status', 'updated_at', 'id'], unique=False)
    op.create_table('automation_workflow_versions',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_automation_workflow_versions_valid_version')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_automation_workflow_versions_created_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workflow_id', 'business_id'], ['automation_workflows.id', 'automation_workflows.business_id'], name='fk_automation_versions_workflow_business', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_workflow_versions')),
    sa.UniqueConstraint('id', 'business_id', 'workflow_id', name='uq_automation_versions_id_business_workflow'),
    sa.UniqueConstraint('workflow_id', 'version', name='uq_automation_versions_workflow_version')
    )
    op.create_index('ix_automation_versions_business_workflow_version', 'automation_workflow_versions', ['business_id', 'workflow_id', 'version'], unique=False)
    op.create_table('automation_nodes',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_version_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.Uuid(), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('configuration', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('position_x', sa.Integer(), server_default='0', nullable=False),
    sa.Column('position_y', sa.Integer(), server_default='0', nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(configuration) = 'object'", name=op.f('ck_automation_nodes_valid_configuration')),
    sa.CheckConstraint("node_type IN ('trigger','condition','branch','action','delay','approval','ai','internal_operation','end')", name=op.f('ck_automation_nodes_valid_node_type')),
    sa.CheckConstraint('char_length(btrim(name)) BETWEEN 1 AND 180', name=op.f('ck_automation_nodes_valid_name')),
    sa.CheckConstraint('order_index BETWEEN 0 AND 10000', name=op.f('ck_automation_nodes_valid_order')),
    sa.CheckConstraint('position_x BETWEEN -100000 AND 100000 AND position_y BETWEEN -100000 AND 100000', name=op.f('ck_automation_nodes_valid_position')),
    sa.ForeignKeyConstraint(['workflow_version_id', 'business_id', 'workflow_id'], ['automation_workflow_versions.id', 'automation_workflow_versions.business_id', 'automation_workflow_versions.workflow_id'], name='fk_automation_nodes_version_business_workflow', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_nodes')),
    sa.UniqueConstraint('id', 'business_id', 'workflow_version_id', name='uq_automation_nodes_id_business_version'),
    sa.UniqueConstraint('workflow_version_id', 'node_key', 'business_id', name='uq_automation_nodes_version_key_business')
    )
    op.create_index('ix_automation_nodes_business_version_order', 'automation_nodes', ['business_id', 'workflow_version_id', 'order_index', 'id'], unique=False)
    op.create_table('automation_workflow_runs',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_version_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_event_id', sa.Uuid(), nullable=True),
    sa.Column('trigger_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), server_default='queued', nullable=False),
    sa.Column('context_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('current_node_key', sa.Uuid(), nullable=True),
    sa.Column('waiting_reason', sa.String(length=32), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('requested_by_user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("jsonb_typeof(context_payload) = 'object'", name=op.f('ck_automation_workflow_runs_valid_context_payload')),
    sa.CheckConstraint("status IN ('queued','running','waiting','succeeded','failed','canceled')", name=op.f('ck_automation_workflow_runs_valid_status')),
    sa.CheckConstraint("trigger_type IN ('event','schedule','manual')", name=op.f('ck_automation_workflow_runs_valid_trigger_type')),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_automation_workflow_runs_valid_completion')),
    sa.CheckConstraint('completed_at IS NULL OR started_at IS NOT NULL', name=op.f('ck_automation_workflow_runs_completion_requires_start')),
    sa.CheckConstraint('failure_code IS NULL OR char_length(btrim(failure_code)) BETWEEN 1 AND 64', name=op.f('ck_automation_workflow_runs_valid_failure_code')),
    sa.CheckConstraint('idempotency_key IS NULL OR char_length(btrim(idempotency_key)) BETWEEN 1 AND 128', name=op.f('ck_automation_workflow_runs_valid_idempotency_key')),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], name=op.f('fk_automation_workflow_runs_requested_by_user_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['trigger_event_id', 'business_id'], ['automation_events.id', 'automation_events.business_id'], name='fk_automation_runs_event_business'),
    sa.ForeignKeyConstraint(['workflow_id', 'business_id'], ['automation_workflows.id', 'automation_workflows.business_id'], name='fk_automation_runs_workflow_business', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id', 'business_id', 'workflow_id'], ['automation_workflow_versions.id', 'automation_workflow_versions.business_id', 'automation_workflow_versions.workflow_id'], name='fk_automation_runs_version_business_workflow'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_workflow_runs')),
    sa.UniqueConstraint('business_id', 'idempotency_key', name='uq_automation_runs_business_idempotency'),
    sa.UniqueConstraint('id', 'business_id', 'workflow_version_id', name='uq_automation_runs_id_business_version'),
    sa.UniqueConstraint('workflow_version_id', 'trigger_event_id', name='uq_automation_runs_version_event')
    )
    op.create_index('ix_automation_runs_business_status_created', 'automation_workflow_runs', ['business_id', 'status', 'created_at', 'id'], unique=False)
    op.create_index('ix_automation_runs_business_workflow_created', 'automation_workflow_runs', ['business_id', 'workflow_id', 'created_at', 'id'], unique=False)
    op.create_table('automation_edges',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_version_id', sa.Uuid(), nullable=False),
    sa.Column('edge_key', sa.Uuid(), nullable=False),
    sa.Column('source_node_key', sa.Uuid(), nullable=False),
    sa.Column('target_node_key', sa.Uuid(), nullable=False),
    sa.Column('branch_label', sa.String(length=64), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('branch_label IS NULL OR char_length(btrim(branch_label)) BETWEEN 1 AND 64', name=op.f('ck_automation_edges_valid_branch_label')),
    sa.CheckConstraint('order_index BETWEEN 0 AND 10000', name=op.f('ck_automation_edges_valid_order')),
    sa.CheckConstraint('source_node_key <> target_node_key', name=op.f('ck_automation_edges_no_self_edge')),
    sa.ForeignKeyConstraint(['workflow_version_id', 'business_id', 'workflow_id'], ['automation_workflow_versions.id', 'automation_workflow_versions.business_id', 'automation_workflow_versions.workflow_id'], name='fk_automation_edges_version_business_workflow', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id', 'source_node_key', 'business_id'], ['automation_nodes.workflow_version_id', 'automation_nodes.node_key', 'automation_nodes.business_id'], name='fk_automation_edges_source_node', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id', 'target_node_key', 'business_id'], ['automation_nodes.workflow_version_id', 'automation_nodes.node_key', 'automation_nodes.business_id'], name='fk_automation_edges_target_node', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_edges')),
    sa.UniqueConstraint('id', 'business_id', 'workflow_version_id', name='uq_automation_edges_id_business_version'),
    sa.UniqueConstraint('workflow_version_id', 'source_node_key', 'branch_label', name='uq_automation_edges_source_branch')
    )
    op.create_index('ix_automation_edges_business_version_source', 'automation_edges', ['business_id', 'workflow_version_id', 'source_node_key', 'order_index'], unique=False)
    op.create_table('automation_node_runs',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_version_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_run_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='1', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('branch_outcome', sa.String(length=64), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('resume_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('running','succeeded','waiting','failed','skipped','canceled')", name=op.f('ck_automation_node_runs_valid_status')),
    sa.CheckConstraint('attempt BETWEEN 1 AND 3', name=op.f('ck_automation_node_runs_valid_attempt')),
    sa.CheckConstraint('branch_outcome IS NULL OR char_length(btrim(branch_outcome)) BETWEEN 1 AND 64', name=op.f('ck_automation_node_runs_valid_branch_outcome')),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= started_at', name=op.f('ck_automation_node_runs_valid_completion')),
    sa.CheckConstraint('failure_code IS NULL OR char_length(btrim(failure_code)) BETWEEN 1 AND 64', name=op.f('ck_automation_node_runs_valid_failure_code')),
    sa.CheckConstraint('result_summary IS NULL OR char_length(result_summary) <= 2000', name=op.f('ck_automation_node_runs_valid_result_summary')),
    sa.ForeignKeyConstraint(['action_id', 'business_id'], ['ai_actions.id', 'ai_actions.business_id'], name='fk_automation_node_runs_action_business'),
    sa.ForeignKeyConstraint(['workflow_run_id', 'business_id', 'workflow_version_id'], ['automation_workflow_runs.id', 'automation_workflow_runs.business_id', 'automation_workflow_runs.workflow_version_id'], name='fk_automation_node_runs_run_business_version', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_version_id', 'node_key', 'business_id'], ['automation_nodes.workflow_version_id', 'automation_nodes.node_key', 'automation_nodes.business_id'], name='fk_automation_node_runs_node'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_automation_node_runs')),
    sa.UniqueConstraint('id', 'business_id', name='uq_automation_node_runs_id_business'),
    sa.UniqueConstraint('workflow_run_id', 'node_key', 'attempt', name='uq_automation_node_runs_node_attempt')
    )
    op.create_index('ix_automation_node_runs_business_run_created', 'automation_node_runs', ['business_id', 'workflow_run_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_automation_node_runs_business_status_resume', 'automation_node_runs', ['business_id', 'status', 'resume_at', 'id'], unique=False)
    op.add_column('approval_requests', sa.Column('workflow_node_run_id', sa.Uuid(), nullable=True))
    op.alter_column('approval_requests', 'action_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index('ix_approval_requests_one_pending_workflow_node', 'approval_requests', ['workflow_node_run_id'], unique=True, postgresql_where=sa.text("status = 'pending' AND workflow_node_run_id IS NOT NULL"))
    op.create_foreign_key('fk_approval_requests_workflow_node_run_business', 'approval_requests', 'automation_node_runs', ['workflow_node_run_id', 'business_id'], ['id', 'business_id'], ondelete='CASCADE')
    op.create_check_constraint(op.f('ck_approval_requests_exactly_one_target'), 'approval_requests', '(action_id IS NOT NULL)::integer + (workflow_node_run_id IS NOT NULL)::integer = 1')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_approval_requests_exactly_one_target'), 'approval_requests', type_='check')
    op.drop_constraint('fk_approval_requests_workflow_node_run_business', 'approval_requests', type_='foreignkey')
    op.drop_index('ix_approval_requests_one_pending_workflow_node', table_name='approval_requests', postgresql_where=sa.text("status = 'pending' AND workflow_node_run_id IS NOT NULL"))
    op.alter_column('approval_requests', 'action_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('approval_requests', 'workflow_node_run_id')
    op.drop_index('ix_automation_node_runs_business_status_resume', table_name='automation_node_runs')
    op.drop_index('ix_automation_node_runs_business_run_created', table_name='automation_node_runs')
    op.drop_table('automation_node_runs')
    op.drop_index('ix_automation_edges_business_version_source', table_name='automation_edges')
    op.drop_table('automation_edges')
    op.drop_index('ix_automation_runs_business_workflow_created', table_name='automation_workflow_runs')
    op.drop_index('ix_automation_runs_business_status_created', table_name='automation_workflow_runs')
    op.drop_table('automation_workflow_runs')
    op.drop_index('ix_automation_nodes_business_version_order', table_name='automation_nodes')
    op.drop_table('automation_nodes')
    op.drop_index('ix_automation_versions_business_workflow_version', table_name='automation_workflow_versions')
    op.drop_table('automation_workflow_versions')
    op.drop_index('ix_automation_workflows_business_status_updated', table_name='automation_workflows')
    op.drop_index('ix_automation_workflows_business_next_run', table_name='automation_workflows')
    op.drop_table('automation_workflows')
    op.drop_index('ix_automation_events_business_type_occurred', table_name='automation_events')
    op.drop_index('ix_automation_events_business_status_occurred', table_name='automation_events')
    op.drop_table('automation_events')
    # ### end Alembic commands ###
