"""add ai action foundation

Revision ID: c2c7d7752db5
Revises: 34cf6a541b22
Create Date: 2026-08-22 15:54:13.765195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2c7d7752db5'
down_revision: Union[str, Sequence[str], None] = '34cf6a541b22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_actions',
    sa.Column('business_id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('proposal_index', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('proposed_requires_approval', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='proposed', nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('policy_decision', sa.String(length=32), nullable=True),
    sa.Column('policy_reason_code', sa.String(length=64), nullable=True),
    sa.Column('policy_evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('execution_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('external_reference_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(status = 'executing' AND execution_started_at IS NOT NULL AND execution_completed_at IS NULL) OR (status IN ('succeeded', 'failed') AND execution_started_at IS NOT NULL AND execution_completed_at IS NOT NULL) OR (status NOT IN ('executing', 'succeeded', 'failed') AND execution_started_at IS NULL AND execution_completed_at IS NULL)", name=op.f('ck_ai_actions_valid_execution_timing_state')),
    sa.CheckConstraint("(status = 'failed' AND failure_code IS NOT NULL) OR (status <> 'failed' AND failure_code IS NULL)", name=op.f('ck_ai_actions_valid_failure_state')),
    sa.CheckConstraint("jsonb_typeof(action_payload) = 'object'", name=op.f('ck_ai_actions_valid_action_payload')),
    sa.CheckConstraint("policy_decision IS NULL OR policy_decision IN ('allow', 'require_approval', 'block')", name=op.f('ck_ai_actions_valid_policy_decision')),
    sa.CheckConstraint("risk_level IN ('low', 'medium', 'high', 'critical')", name=op.f('ck_ai_actions_valid_risk_level')),
    sa.CheckConstraint("status <> 'blocked' OR policy_decision = 'block'", name=op.f('ck_ai_actions_blocked_requires_block_policy')),
    sa.CheckConstraint("status <> 'pending_approval' OR policy_decision = 'require_approval'", name=op.f('ck_ai_actions_pending_requires_approval_policy')),
    sa.CheckConstraint("status <> 'proposed' OR policy_decision IS NULL", name=op.f('ck_ai_actions_proposed_has_no_policy_decision')),
    sa.CheckConstraint("status IN ('proposed', 'pending_approval', 'ready', 'blocked', 'rejected', 'expired', 'executing', 'succeeded', 'failed', 'canceled')", name=op.f('ck_ai_actions_valid_status')),
    sa.CheckConstraint("status NOT IN ('ready', 'executing', 'succeeded', 'failed') OR policy_decision IN ('allow', 'require_approval')", name=op.f('ck_ai_actions_executable_state_requires_allowing_policy')),
    sa.CheckConstraint("status NOT IN ('rejected', 'expired') OR policy_decision = 'require_approval'", name=op.f('ck_ai_actions_approval_terminal_requires_approval_policy')),
    sa.CheckConstraint('(policy_decision IS NULL AND policy_evaluated_at IS NULL) OR (policy_decision IS NOT NULL AND policy_evaluated_at IS NOT NULL)', name=op.f('ck_ai_actions_consistent_policy_evaluation')),
    sa.CheckConstraint('char_length(btrim(action_type)) BETWEEN 1 AND 100', name=op.f('ck_ai_actions_valid_action_type')),
    sa.CheckConstraint('char_length(btrim(description)) BETWEEN 1 AND 2000', name=op.f('ck_ai_actions_valid_description')),
    sa.CheckConstraint('execution_completed_at IS NULL OR execution_completed_at >= execution_started_at', name=op.f('ck_ai_actions_valid_execution_completion_time')),
    sa.CheckConstraint('execution_completed_at IS NULL OR execution_started_at IS NOT NULL', name=op.f('ck_ai_actions_completion_requires_start')),
    sa.CheckConstraint('external_reference_id IS NULL OR char_length(btrim(external_reference_id)) BETWEEN 1 AND 255', name=op.f('ck_ai_actions_valid_external_reference_id')),
    sa.CheckConstraint('failure_code IS NULL OR char_length(btrim(failure_code)) BETWEEN 1 AND 64', name=op.f('ck_ai_actions_valid_failure_code')),
    sa.CheckConstraint('policy_reason_code IS NULL OR char_length(btrim(policy_reason_code)) BETWEEN 1 AND 64', name=op.f('ck_ai_actions_valid_policy_reason_code')),
    sa.CheckConstraint('proposal_index >= 0 AND proposal_index < 20', name=op.f('ck_ai_actions_valid_proposal_index')),
    sa.CheckConstraint('result_summary IS NULL OR char_length(btrim(result_summary)) BETWEEN 1 AND 2000', name=op.f('ck_ai_actions_valid_result_summary')),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], name=op.f('fk_ai_actions_business_id_businesses'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['execution_id'], ['ai_agent_executions.id'], name=op.f('fk_ai_actions_execution_id_ai_agent_executions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_actions')),
    sa.UniqueConstraint('execution_id', 'proposal_index', name='uq_ai_actions_execution_proposal')
    )
    op.create_index('ix_ai_actions_business_created', 'ai_actions', ['business_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_ai_actions_business_status_created', 'ai_actions', ['business_id', 'status', 'created_at', 'id'], unique=False)
    op.create_index('ix_ai_actions_business_type_created', 'ai_actions', ['business_id', 'action_type', 'created_at', 'id'], unique=False)
    op.create_index('ix_ai_actions_execution_created', 'ai_actions', ['execution_id', 'created_at', 'id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_actions_execution_created', table_name='ai_actions')
    op.drop_index('ix_ai_actions_business_type_created', table_name='ai_actions')
    op.drop_index('ix_ai_actions_business_status_created', table_name='ai_actions')
    op.drop_index('ix_ai_actions_business_created', table_name='ai_actions')
    op.drop_table('ai_actions')
    # ### end Alembic commands ###
